### PR TITLE
big reformat

### PR DESCRIPTION
**Pull request by huangp**

### CODE REVIEW

**Comment by seanf** [comment]
@huangp is this a pure reformat?

**Comment by huangp** [comment]
Yes as far as I remember. Unless IntelliJ did not do a proper job.

**Comment by seanf** [comment]
Looks to be safe according to https://github.com/zanata/jgettext/commit/9a0b9c9cb5d4298cf7164ae4d10f7a65f197a453?w=1
(although some import statements were changed slightly).

:+1:

**Comment by davidmason** [comment]
@huangp looks like this may be good to merge now, is anything holding it up?

**Pull request merged**
